# Generated by Django 5.0.7 on 2026-06-09 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=24)),
                ('password_hash', models.CharField(max_length=64)),
                ('credits', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('active', '正常'), ('disabled', '禁用')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='AI 助手', max_length=24)),
                ('total_available_credits', models.DecimalField(decimal_places=2, default=10000, max_digits=12)),
                ('welcome_credits', models.DecimalField(decimal_places=2, default=20, max_digits=12)),
                ('chat_cost', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('image_cost', models.DecimalField(decimal_places=2, default=5, max_digits=12)),
                ('wechat_pay_text', models.TextField(default='请替换为你的微信收款码或收款说明')),
                ('alipay_text', models.TextField(default='请替换为你的支付宝收款码或收款说明')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('mode', models.CharField(choices=[('chat', '聊天'), ('image', '生图')], default='chat', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aiuser')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '助手')], max_length=16)),
                ('type', models.CharField(choices=[('text', '文本'), ('image', '图片')], default='text', max_length=16)),
                ('content', models.TextField()),
                ('image_url', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('wechat', '微信'), ('alipay', '支付宝')], max_length=16)),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认')], default='pending', max_length=16)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aiuser')),
            ],
        ),
        migrations.CreateModel(
            name='SessionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('role', models.CharField(choices=[('user', '用户'), ('admin', '管理员')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.aiuser')),
            ],
        ),
    ]
