# Generated by Codex on 2026-06-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_appsetting_ai_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiuser",
            name="status",
            field=models.CharField(
                choices=[("pending", "待审核"), ("active", "正常"), ("disabled", "禁用")],
                default="pending",
                max_length=16,
            ),
        ),
    ]
